name: Update README

on:
  push:
    branches:
      - main # or the branch you want to monitor

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "Updating README file"
          # Insert your script or command to update the README file here
          # For example, you can use echo to append the current date and time
          echo "Last updated: $(date)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README file automatically"
          git push
